# Generated by Django 4.2.1 on 2023-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
